#!/usr/bin/env bash
set -euo pipefail

FORK_ROOT="/home/frnlx/end4files/end4-dotfiles"
UPSTREAM_ROOT="/home/frnlx/end4files/dots-hyprland"
UPSTREAM_COMMIT="47235ac4"

cd "$FORK_ROOT"

echo "=============================================="
echo "  SYNCING FILES FROM UPSTREAM"
echo "=============================================="
echo "  Upstream: $UPSTREAM_ROOT"
echo "  Target commit: $UPSTREAM_COMMIT"
echo "=============================================="
echo ""

files=(
    ".github/README.md"
    ".github/workflows/moderator.yml"
    "diagnose"
    "dots/.config/fish/config.fish"
    "dots/.config/hypr/custom/env.conf"
    "dots/.config/hypr/custom/execs.conf"
    "dots/.config/hypr/custom/general.conf"
    "dots/.config/hypr/custom/keybinds.conf"
    "dots/.config/hypr/custom/rules.conf"
    "dots/.config/hypr/custom/variables.conf"
    "dots/.config/hypr/hyprland.conf"
    "dots/.config/hypr/hyprland/env.conf"
    "dots/.config/hypr/hyprland/general.conf"
    "dots/.config/hypr/hyprland/keybinds.conf"
    "dots/.config/hypr/hyprland/rules.conf"
    "dots/.config/hypr/hyprland/variables.conf"
    "dots/.config/matugen/templates/gtk-4.0/gtk.css"
    "dots/.config/matugen/templates/hyprland/colors.conf"
    "dots/.config/quickshell/ii/GlobalStates.qml"
    "dots/.config/quickshell/ii/defaults/ai/prompts/ii-Default.md"
    "dots/.config/quickshell/ii/modules/common/Appearance.qml"
    "dots/.config/quickshell/ii/modules/common/Config.qml"
    "dots/.config/quickshell/ii/modules/common/Icons.qml"
    "dots/.config/quickshell/ii/modules/common/functions/ColorUtils.qml"
    "dots/.config/quickshell/ii/modules/common/models/gCloud/GCloudApi.qml"
    "dots/.config/quickshell/ii/modules/common/models/gCloud/GCloudTranslate.qml"
    "dots/.config/quickshell/ii/modules/common/models/gCloud/GCloudVision.qml"
    "dots/.config/quickshell/ii/modules/common/models/gCloud/GCloudVisionResult.qml"
    "dots/.config/quickshell/ii/modules/common/models/quickToggles/NightLightToggle.qml"
    "dots/.config/quickshell/ii/modules/common/utils/MultiTurnProcess.qml"
    "dots/.config/quickshell/ii/modules/common/utils/ScreenshotAction.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ButtonGroup.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ContentPage.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ContentSection.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ContentSubsection.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ErrorShakeAnimation.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/MaskMultiEffect.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/NavigationRailTabArray.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/NoticeBox.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/Revealer.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ScrollEdgeFade.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/SqueezedAnnotationStyledText.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/StyledSlider.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/Toolbar.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/ToolbarPairedFab.qml"
    "dots/.config/quickshell/ii/modules/common/widgets/WindowDialog.qml"
    "dots/.config/quickshell/ii/modules/ii/background/Background.qml"
    "dots/.config/quickshell/ii/modules/ii/bar/BarContent.qml"
    "dots/.config/quickshell/ii/modules/ii/bar/SysTray.qml"
    "dots/.config/quickshell/ii/modules/ii/bar/SysTrayItem.qml"
    "dots/.config/quickshell/ii/modules/ii/bar/SysTrayMenu.qml"
    "dots/.config/quickshell/ii/modules/ii/dock/DockApps.qml"
    "dots/.config/quickshell/ii/modules/ii/lock/Lock.qml"
    "dots/.config/quickshell/ii/modules/ii/lock/LockSurface.qml"
    "dots/.config/quickshell/ii/modules/ii/onScreenDisplay/OnScreenDisplay.qml"
    "dots/.config/quickshell/ii/modules/ii/onScreenDisplay/OsdValueIndicator.qml"
    "dots/.config/quickshell/ii/modules/ii/onScreenDisplay/indicators/BrightnessIndicator.qml"
    "dots/.config/quickshell/ii/modules/ii/onScreenDisplay/indicators/GammaIndicator.qml"
    "dots/.config/quickshell/ii/modules/ii/overview/OverviewWidget.qml"
    "dots/.config/quickshell/ii/modules/ii/overview/SearchItem.qml"
    "dots/.config/quickshell/ii/modules/ii/regionSelector/RectCornersSelectionDetails.qml"
    "dots/.config/quickshell/ii/modules/ii/regionSelector/RegionSelection.qml"
    "dots/.config/quickshell/ii/modules/ii/regionSelector/RegionSelector.qml"
    "dots/.config/quickshell/ii/modules/ii/screenCorners/ScreenCorners.qml"
    "dots/.config/quickshell/ii/modules/ii/screenTranslator/ScreenTextOverlay.qml"
    "dots/.config/quickshell/ii/modules/ii/screenTranslator/ScreenTranslator.qml"
    "dots/.config/quickshell/ii/modules/ii/screenTranslator/ScreenTranslatorPanel.qml"
    "dots/.config/quickshell/ii/modules/ii/sidebarRight/QuickSliders.qml"
    "dots/.config/quickshell/ii/modules/ii/sidebarRight/bluetoothDevices/BluetoothDeviceItem.qml"
    "dots/.config/quickshell/ii/modules/ii/sidebarRight/nightLight/NightLightDialog.qml"
    "dots/.config/quickshell/ii/modules/ii/sidebarRight/quickToggles/classicStyle/NightLight.qml"
    "dots/.config/quickshell/ii/modules/ii/sidebarRight/volumeMixer/VolumeMixerEntry.qml"
    "dots/.config/quickshell/ii/modules/ii/verticalBar/BatteryIndicator.qml"
    "dots/.config/quickshell/ii/modules/ii/verticalBar/VerticalBarContent.qml"
    "dots/.config/quickshell/ii/modules/ii/verticalBar/VerticalClockWidget.qml"
    "dots/.config/quickshell/ii/modules/ii/verticalBar/VerticalDateWidget.qml"
    "dots/.config/quickshell/ii/modules/ii/wallpaperSelector/WallpaperSelectorContent.qml"
    "dots/.config/quickshell/ii/modules/settings/BackgroundConfig.qml"
    "dots/.config/quickshell/ii/modules/waffle/actionCenter/nightLight/NightLightControl.qml"
    "dots/.config/quickshell/ii/modules/waffle/lock/WaffleLock.qml"
    "dots/.config/quickshell/ii/modules/waffle/looks/WIcons.qml"
    "dots/.config/quickshell/ii/modules/waffle/looks/WToolbar.qml"
    "dots/.config/quickshell/ii/modules/waffle/startMenu/startPage/StartPageApps.qml"
    "dots/.config/quickshell/ii/panelFamilies/IllogicalImpulseFamily.qml"
    "dots/.config/quickshell/ii/panelFamilies/WaffleFamily.qml"
    "dots/.config/quickshell/ii/scripts/colors/applycolor.sh"
    "dots/.config/quickshell/ii/scripts/colors/terminal/kitty-theme.conf"
    "dots/.config/quickshell/ii/scripts/colors/terminal/sequences.txt"
    "dots/.config/quickshell/ii/scripts/hyprland/hyprconfigurator.py"
    "dots/.config/quickshell/ii/scripts/images/text-color-venv.sh"
    "dots/.config/quickshell/ii/scripts/images/text_color.py"
    "dots/.config/quickshell/ii/scripts/musicRecognition/recognize-music.sh"
    "dots/.config/quickshell/ii/services/Brightness.qml"
    "dots/.config/quickshell/ii/services/GoogleCloud.qml"
    "dots/.config/quickshell/ii/services/Hyprsunset.qml"
    "dots/.config/quickshell/ii/services/KeyringStorage.qml"
    "dots/.config/quickshell/ii/services/LauncherSearch.qml"
    "dots/.config/quickshell/ii/services/TrayService.qml"
    "dots/.config/quickshell/ii/services/gCloud/token-from-key-venv.sh"
    "dots/.config/quickshell/ii/services/gCloud/token_from_key.py"
    "dots/.config/quickshell/ii/translations/en_US.json"
    "dots/.config/quickshell/ii/translations/es_MX.json"
    "dots/.config/quickshell/ii/translations/fr_FR.json"
    "dots/.config/quickshell/ii/translations/ru_RU.json"
    "dots/.config/quickshell/ii/translations/zh_CN.json"
    "dots/.config/starship.toml"
    "sdata/deps-info.md"
    "sdata/dist-arch/illogical-impulse-audio/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-backlight/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-basic/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-bibata-modern-classic-bin/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-fonts-themes/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-hyprland/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-kde/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-microtex-git/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-oneui4-icons-git/.gitignore"
    "sdata/dist-arch/illogical-impulse-oneui4-icons-git/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-portal/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-python/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-quickshell-git/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-screencapture/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-toolkit/PKGBUILD"
    "sdata/dist-arch/illogical-impulse-widgets/PKGBUILD"
    "sdata/dist-arch/install-deps.sh"
    "sdata/dist-arch/uninstall-deps.sh"
    "sdata/dist-fedora/SPECS/cpptrace.spec"
    "sdata/dist-fedora/SPECS/hyprland-qt-support.spec"
    "sdata/dist-fedora/SPECS/matugen.spec"
    "sdata/dist-fedora/SPECS/quickshell-git.spec"
    "sdata/dist-fedora/feddeps.toml"
    "sdata/dist-fedora/install-deps.sh"
    "sdata/dist-gentoo/illogical-impulse-oneui4-icons-git/illogical-impulse-oneui4-icons-git-1.0-r1.ebuild"
    "sdata/dist-gentoo/illogical-impulse-quickshell-git/illogical-impulse-quickshell-git-0.1.0-r6.ebuild"
    "sdata/dist-gentoo/illogical-impulse-widgets/illogical-impulse-widgets-1.0-r5.ebuild"
    "sdata/dist-gentoo/import-local-pkgs.sh"
    "sdata/dist-gentoo/install-deps.sh"
    "sdata/dist-gentoo/keywords"
    "sdata/dist-gentoo/local-pkgs/widgets/songrec-0.4.3-r1.ebuild"
    "sdata/dist-gentoo/uninstall-deps.sh"
    "sdata/dist-gentoo/useflags"
    "sdata/dist-nix/home-manager/flake.nix"
    "sdata/dist-nix/home-manager/home.nix"
    "sdata/dist-nix/home-manager/quickshell.nix"
    "sdata/lib/dist-determine.sh"
    "sdata/lib/functions.sh"
    "sdata/lib/package-installers.sh"
    "sdata/subcmd-install/3.files-exp.yaml"
    "sdata/subcmd-install/3.files-legacy.sh"
    "sdata/subcmd-install/3.files.sh"
    "sdata/subcmd-install/options.sh"
    "sdata/uv/requirements.in"
    "sdata/uv/requirements.txt"
)

# Do the sync
echo "Copying ${#files[@]} files from upstream..."
for file in "${files[@]}"; do
    if [ -f "$UPSTREAM_ROOT/$file" ]; then
        mkdir -p "$(dirname "$file")"
        cp "$UPSTREAM_ROOT/$file" "$file"
        echo "[SYNCED] $file"
    else
        echo "[SKIPPED] $file (No longer exists in upstream)"
        # Optionally removing from fork
        rm -f "$file" || true
    fi
done

echo ""
echo "Sync complete!"
